#include "../inc/theme.h"

namespace Theme {
void apply(QWidget* root, bool darkMode)
{
    if (darkMode) {
        root->setStyleSheet(
            "QMainWindow, QWidget#centralwidget {"
            "  color: rgb(255, 255, 255);"
            "  background-color: rgb(35, 35, 45);"
            "}"
            "QGroupBox {"
            "  background-color: rgb(65, 65, 80);"
            "  border: 1px solid rgb(90, 90, 105);"
            "  border-radius: 5px;"
            "  margin-top: 10px;"
            "  padding-top: 5px;"
            "}"
            "QGroupBox::title {"
            "  subcontrol-origin: margin;"
            "  left: 10px;"
            "  padding: 0 5px;"
            "  color: rgb(255, 255, 255);"
            "}"
            "QLabel {"
            "  color: rgb(255, 255, 255);"
            "}"
            "QCheckBox {"
            "  color: rgb(255, 255, 255);"
            "}"
            "QPushButton {"
            "  background-color: rgb(75, 75, 95);"
            "  border: 1px solid rgb(100, 100, 120);"
            "  border-radius: 4px;"
            "  padding: 5px 10px;"
            "  color: rgb(255, 255, 255);"
            "}"
            "QPushButton:hover {"
            "  background-color: rgb(90, 90, 110);"
            "}"
            "QPushButton#readRom, QPushButton#readSave {"
            "  background-color: rgb(140, 120, 180);"
            "  border: 1px solid rgb(120, 100, 160);"
            "}"
            "QPushButton#readRom:hover, QPushButton#readSave:hover {"
            "  background-color: rgb(155, 135, 195);"
            "}"
            "QPushButton#eraseBySize, QPushButton#eraseFlash {"
            "  background-color: rgb(200, 100, 100);"
            "  border: 1px solid rgb(180, 80, 80);"
            "}"
            "QPushButton#eraseBySize:hover, QPushButton#eraseFlash:hover {"
            "  background-color: rgb(215, 115, 115);"
            "}"
            "QComboBox {"
            "  background-color: rgb(100, 150, 200);"
            "  border: 1px solid rgb(80, 130, 180);"
            "  border-radius: 4px;"
            "  padding: 3px 5px;"
            "  color: rgb(255, 255, 255);"
            "}"
            "QComboBox:hover {"
            "  background-color: rgb(110, 160, 210);"
            "  border: 1px solid rgb(70, 130, 180);"
            "}"
            "QComboBox QAbstractItemView {"
            "  background-color: rgb(65, 65, 80);"
            "  color: rgb(255, 255, 255);"
            "  selection-background-color: rgb(70, 130, 180);"
            "  selection-color: rgb(255, 255, 255);"
            "  border: 1px solid rgb(100, 100, 120);"
            "}"
            "QComboBox::drop-down {"
            "  border: none;"
            "}"
            "QTextBrowser {"
            "  background-color: rgb(55, 55, 70);"
            "  border: 1px solid rgb(90, 90, 105);"
            "  color: rgb(255, 255, 255);"
            "}"
            "QProgressBar {"
            "  background-color: rgb(65, 65, 80);"
            "  border: 1px solid rgb(90, 90, 105);"
            "  border-radius: 4px;"
            "  color: rgb(255, 255, 255);"
            "}"
            "QProgressBar::chunk {"
            "  background-color: rgb(70, 130, 180);"
            "}"
            "selection-color: rgb(255, 255, 255);"
            "selection-background-color: rgb(70, 130, 180);"
        );
    } else {
        root->setStyleSheet(
            "QMainWindow, QWidget#centralwidget {"
            "  color: rgb(40, 40, 50);"
            "  background-color: rgb(255, 255, 255);"
            "}"
            "QGroupBox {"
            "  background-color: rgb(245, 245, 248);"
            "  border: 1px solid rgb(220, 220, 228);"
            "  border-radius: 5px;"
            "  margin-top: 10px;"
            "  padding-top: 5px;"
            "}"
            "QGroupBox::title {"
            "  subcontrol-origin: margin;"
            "  left: 10px;"
            "  padding: 0 5px;"
            "  color: rgb(40, 40, 50);"
            "}"
            "QLabel {"
            "  color: rgb(40, 40, 50);"
            "}"
            "QPushButton {"
            "  background-color: rgb(245, 245, 250);"
            "  border: 1px solid rgb(200, 200, 210);"
            "  border-radius: 4px;"
            "  padding: 5px 10px;"
            "  color: rgb(40, 40, 50);"
            "}"
            "QPushButton:hover {"
            "  background-color: rgb(230, 230, 240);"
            "}"
            "QPushButton#readRom, QPushButton#readSave {"
            "  background-color: rgb(200, 180, 230);"
            "  border: 1px solid rgb(180, 160, 210);"
            "  color: rgb(40, 40, 50);"
            "}"
            "QPushButton#readRom:hover, QPushButton#readSave:hover {"
            "  background-color: rgb(185, 165, 215);"
            "}"
            "QPushButton#eraseBySize, QPushButton#eraseFlash {"
            "  background-color: rgb(240, 150, 150);"
            "  border: 1px solid rgb(220, 130, 130);"
            "  color: rgb(40, 40, 50);"
            "}"
            "QPushButton#eraseBySize:hover, QPushButton#eraseFlash:hover {"
            "  background-color: rgb(230, 135, 135);"
            "}"
            "QComboBox {"
            "  background-color: rgb(180, 210, 240);"
            "  border: 1px solid rgb(140, 180, 220);"
            "  border-radius: 4px;"
            "  padding: 3px 5px;"
            "  color: rgb(40, 40, 50);"
            "}"
            "QComboBox:hover {"
            "  background-color: rgb(160, 195, 230);"
            "  border: 1px solid rgb(100, 160, 210);"
            "}"
            "QComboBox QAbstractItemView {"
            "  background-color: rgb(255, 255, 255);"
            "  color: rgb(40, 40, 50);"
            "  selection-background-color: rgb(70, 130, 180);"
            "  selection-color: rgb(255, 255, 255);"
            "  border: 1px solid rgb(200, 200, 210);"
            "}"
            "QComboBox::drop-down {"
            "  border: none;"
            "}"
            "QTextBrowser {"
            "  background-color: rgb(255, 255, 255);"
            "  border: 1px solid rgb(200, 200, 210);"
            "  color: rgb(40, 40, 50);"
            "}"
            "QProgressBar {"
            "  background-color: rgb(255, 255, 255);"
            "  border: 1px solid rgb(200, 200, 210);"
            "  border-radius: 4px;"
            "  color: rgb(40, 40, 50);"
            "}"
            "QProgressBar::chunk {"
            "  background-color: rgb(70, 130, 180);"
            "}"
            "selection-color: rgb(255, 255, 255);"
            "selection-background-color: rgb(70, 130, 180);"
        );
    }
}
}
